version: "3"

services:
  nginx-proxy:
    container_name: nginx_proxy
    restart: on-failure
    image: nginx:latest
    links:
      - 'nexus'
    volumes:
      - /nexus/nginx-proxy/ssl:/etc/nginx/ssl:ro
      - /nexus/nginx-proxy/conf.d/:/etc/nginx/conf.d
      - /nexus/nginx-proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80'
      - '443:443'
    command: [ 'nginx', '-g', 'daemon off;']

  nexus:
    container_name: nexus
    restart: always
    image: sonatype/nexus3
    volumes:
        - "nexus-data:/nexus-data"
    ports:
        - "8081:8081"

volumes:
  nexus-data: {}
